name: assignment_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  buttons_tabbar: ^1.3.15
  carousel_slider: ^5.0.0
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_any_logo: ^1.1.1
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  http: ^1.3.0
  persistent_bottom_nav_bar: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  text_scroll: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Helvetica
      fonts: 
        - asset: assets/fonts/HelveticaNowMicro-Light.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNowMicro-Regular.ttf
        - asset: assets/fonts/HelveticaNowMicro-Medium.ttf
          weight: 400
    - family: Associate
      fonts: 
        - asset: assets/fonts/AssociateSansRegular.otf
    - family: Cerebri
      fonts: 
        - asset: assets/fonts/Cerebri-Sans-Medium.ttf
    - family: Muli
      fonts: 
        - asset: assets/fonts/muli.regular.ttf
          

