name: assignment_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Helvetica
      fonts: 
        - asset: assets/fonts/HelveticaNowMicro-Light.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNowMicro-Regular.ttf
        - asset: assets/fonts/HelveticaNowMicro-Medium.ttf
          weight: 400

          

