name: screen1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dotted_line: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Denton
      fonts:
       - asset: assets/fonts/DentonTextXCondTest-Bold.otf
    - family: Gilroy
      fonts:
       - asset: assets/fonts/Gilroy-Bold.ttf
       - asset: assets/fonts/Gilroy-Regular.ttf
         weight: 200

